---
stages:
- name: ScriptStage
  inputs:
  - type: git
    branch: master
    service: ${REPO}
  triggers:
  - type: commit
  properties:
  - name: API_UNDER_TEST
    value: "http://atestapi.mybluemix.net/"
    type: text
  jobs:
  - name: CurlScriptJob
    type: builder
    script: |
      #!/bin/bash
      echo -e "----------------------------------------------------------------------------------"
      echo "Using curl to test site: $API_UNDER_TEST"
      curl http://atestapi.mybluemix.net/api.php?command=testTipOfTheDay&whichDay=test
      #curl --help
