---
stages:
- name: ScriptStage
  inputs:
  - type: git
    branch: master
    service: ${REPO}
  triggers:
  - type: commit
  properties:
  - name: API_UNDER_TEST
    value: "http://example.com"
    type: text
  jobs:
  - name: CurlScriptJob
    type: builder
    script: |
      #!/bin/bash
      echo -e "----------------------------------------------------------------------------------"
      echo "Using curl to test site: $API_UNDER_TEST"
      curl -r 0-63 $API_UNDER_TEST
      #curl --help
